server:
  port: 9090

spring:
  application:
    name: userservice

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/fitness-db
    username: dbuser
    password: dbpassword
    hikari:
      schema: userservice
      idle-timeout: 120000
      max-lifetime: 300000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
    show-sql: true

  liquibase:
    enabled: true
    default-schema: userservice
    change-log: classpath:/db/changelog/db.changelog-master.yaml

grpc:
  port: 6565